### ISSUE TITLE
KODI add-on 

### ISSUE THREAD

**Issue by BelowBasic** [BelowBasic/WikipediaScraper#2]
Check out how to implement a KODI add-on and what we have to pay special attention to.

**Comment by BelowBasic** [comment]
https://kodi.wiki/view/Python_libraries

**Comment by BelowBasic** [comment]
Project Structure of a Kodi Addon
```
addon.py
addon.xml
LICENSE.txt
resources/
  settings.xml
  language/
  lib/
  data/
  media/
  fanart.jpg (can be placed anywhere in the addon directory)
  icon.png (can be placed anywhere in the addon directory)
  banner.jpg (optional - can be placed anywhere in the addon directory)
  clearlogo.png (optional - can be placed anywhere in the addon directory)
  screenshot-1.jpg (optional - can be placed anywhere in the addon directory)
  screenshot-2.jpg (optional - can be placed anywhere in the addon directory)
  screenshot-3.jpg (optional - can be placed anywhere in the addon directory)
  screenshot-4.jpg (optional - can be placed anywhere in the addon directory)
```

**Comment by BelowBasic** [comment]
If you already have installed a Kodi addon, you can edit this addon live in the appdata/roaming/Kodi/addons/<youraddon> to update it.

If you try to uninstall the addon & reinstall it via zipfile, you will get an Error until you restart the Kodi application.

**Comment by wichris** [comment]
Created a Branch for the Hello World addon.

It's important to name the ZIP folder and the id in the XML file (line 2) the same.

**Comment by JordanWalther** [comment]
> Created a Branch for the Hello World addon.
> 
> It's important to name the ZIP folder and the id in the XML file (line 2) the same.

During ZIP installation procedure in kodi, also make sure that the ZIP folder only contains the 'addon' directory with specific files on top level.
